name: Build and Test

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - 'feat/**'
      - release-candidate
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux-test:
    # Change to buildjet-16vcpu-ubuntu-2204 for a more powerful runner (GitHub App must be enabled)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - name: Linux Tests
        run: |
          cargo nextest run --profile ci --cargo-profile dev-ci --workspace

  # Wasm build, rustfmt, clippy, doctests, and MSRV
  code-quality:
    uses: lurk-lab/ci-workflows/.github/workflows/lints.yml@main

  # Check documentation links aren't broken
  link-checker:
    uses: lurk-lab/ci-workflows/.github/workflows/links-check.yml@main
    with: 
      fail-fast: true

  # Lint dependencies for licensing and auditing issues as per `deny.toml`
  licenses-audits:
    uses: lurk-lab/ci-workflows/.github/workflows/licenses-audits.yml@main
